### ISSUE TITLE
Date doesn't seem to be updating

### ISSUE THREAD

**Issue by kmorey** [romannurik/FORMWatchFace#2]
My watch currently says TUE 26 for the date, but it's the evening of Friday the 29th.

Looking at the code, it appears to be grabbing a new Calendar instance during each time tick, so I'm not sure why it's not updating on the display.

**Comment by frigus02** [comment]
I have the same issue. The date does not refresh.

My workaround is currently to change the watch face to something else and then back to the FORM watch face.

**Comment by romannurik** [comment]
Not quite sure what's going on but looks like a lot of people are running into this...

**Comment by physphil** [comment]
Having the same problem as well, Moto 360 and Nexus 5. I have to change the watch face and change it back in order to get the correct date.

**Comment by romannurik** [comment]
Looks like I'm only calling `updateDateStr` in `onTimeTick`, which only triggers in ambient mode. Watches that don't use ambient mode will thus not update correctly. Will fix.

**Comment by kmorey** [comment]
Turning on ambient mode just now did cause the date to update for me.

**Comment by romannurik** [comment]
Should be fixed in 1.0.2, just pushed to Play.
