### ISSUE TITLE
Listen to timezone changes

### ISSUE THREAD

**Issue by QuirijnGB** [romannurik/FORMWatchFace#3]
The time doesn't update when you change the timezone on the phone.

It updates if you switch to another watch and back

Found on GWatch R

**Comment by romannurik** [comment]
It might take a few seconds for the phone to send the update to the watch (and this is done at the system level). Does this issue occur with other watch faces?

**Comment by QuirijnGB** [comment]
Other watch faces update immediately.
I noticed it when flying back from the US. Didn't update after being in the Netherlands for a couple of hours

**Comment by romannurik** [comment]
Oh, sorry, I misread the issue. Working on a fix.

**Comment by romannurik** [comment]
Fixed in ccd11a51b6c609c356ea42dec568332a7ce2730b
